services:
  - type: web
    name: access-control-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn projectname.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectname.settings
